title:            Code craft.
description:      Opinionated ramblings on the art and science of software development.
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://localhost:4000
url:              http://www.joaofernandes.eu
disqus_shortname:

# Owner/author information
owner:
  name:           João Fernandes
  avatar:         bio-photo.jpg
  bio:            "Bald. Happy. Car lover. Software engineer at Talkdesk."
  email:
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook:       jcmfernandes
  github:         jcmfernandes
  stackoverflow:
  linkedin:       jcmfernandes
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
#  - title: Made Mistakes
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Lisbon
future:      true
show_drafts: false
#pygments:    true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
